name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: dugleelabs/github-workflows/.github/workflows/duglee-semantic-release.yaml@main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.DUGLEEBOT_TOKEN }}
