import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'

export function registerPrompts(server: McpServer): void {
  server.prompt(
    'dugleelabs/create-blog-from-topic',
    'Research a topic and create a draft blog post in Strapi',
    {
      topic: z.string().describe('The topic to research and write about'),
      contentType: z
        .string()
        .optional()
        .describe('Strapi content type to save the draft in (default: articles)'),
    },
    ({ topic, contentType }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              'Please research the following topic and create a draft blog post, then save it to Strapi.',
              '',
              `Topic: ${topic}`,
              `Content type: ${contentType ?? 'articles'}`,
              '',
              '## Steps',
              '',
              '1. Use research_topic to gather current information on the topic',
              '2. Act as an SEO expert and run multiple research_topic calls to build a comprehensive keyword strategy:',
              '   - "[topic] best keywords 2025" — find high-value primary and secondary keywords',
              '   - "[topic] long tail keywords" — find specific, lower-competition phrases readers actually search',
              '   - "[topic] related questions people ask" — find question-based keywords (who, what, how, why)',
              '   - "[topic] trending searches" — find rising keywords with current momentum',
              '   - Analyse all results to identify: primary keyword, secondary keywords, long-tail phrases, LSI (latent semantic indexing) terms, and question-based keywords',
              '   - Note search intent (informational, navigational, commercial, transactional) for the primary keyword',
              '3. Use research_topic again with a query like "[topic] featured image site:unsplash.com OR site:pexels.com" to find:',
              '   - A cover/featured image for the article',
              '   - Additional inline images that can be placed between sections to illustrate key points',
              '4. Use generate_draft with:',
              '   - researchResults: the content research from step 1',
              '   - imageUrls: all image URLs found in step 3 (first = cover, rest = inline)',
              '   - keywords: the full comma-separated keyword list from step 2 (primary first)',
              '   The tool will weave keywords, images, references, and community engagement into the article automatically',
              `5. Use get_content_type_schema to check the field names for "${contentType ?? 'articles'}"`,
              '6. Use create_entry to save the draft with the full data payload including the seo component (see SEO guidelines below). Do not publish — leave as draft.',
              '7. Return the Strapi admin URL, the cover image URL, the keyword strategy summary, and a brief summary of the draft',
              '',
              '## Writing Guidelines',
              '',
              'The article must feel like it comes from a real person with a strong point of view — not a content mill.',
              '',
              '**Voice & tone**',
              '- Write as a personal viewpoint, critique, or practical guide — not a neutral summary',
              '- Take a clear stance. Agree, disagree, or offer a nuanced take — do not sit on the fence',
              '- Use "we" and "our" to reflect the dugleelabs perspective where appropriate',
              '- Be direct and opinionated. Avoid hedging language like "it could be said" or "some may argue"',
              '',
              '**Structure**',
              '- Open with a hook that states the point of view immediately',
              '- Use H2/H3 headings to break the article into scannable sections',
              '- Insert inline images between sections where they add context — use Markdown image syntax: ![alt text](image-url)',
              '- End with a conclusion that reinforces the main argument',
              '',
              '**References & backlinks**',
              '- Cite sources inline as Markdown links where facts or quotes are used',
              '- Add a "## References" section at the bottom with numbered backlinks to all sources used from research results',
              '- Where relevant, link back to dugleelabs.io — for example: "We covered a related topic in depth at [dugleelabs.io](https://dugleelabs.io)"',
              '',
              '**Community engagement**',
              '- End the article with a "## Join the Conversation" section',
              '- Pose 1–2 open questions to the reader to invite comments or replies',
              '- Invite readers to share their experience or opinion on the topic',
              '- Mention that dugleelabs publishes regular takes on this space and link to https://dugleelabs.io',
              '',
              '## SEO Guidelines',
              '',
              'You are acting as an SEO expert. Apply the full keyword strategy from step 2 when populating every SEO field.',
              '',
              '**Keyword placement rules:**',
              '- Primary keyword must appear in: article title, seoTitle, first 100 words of body, at least one H2 heading, metaDescription',
              '- Secondary keywords must appear naturally across H2/H3 headings and body paragraphs',
              '- Long-tail phrases should be worked into subheadings and the conclusion',
              '- Question-based keywords should map to dedicated H2/H3 sections (ideal for featured snippets)',
              '- LSI terms should be distributed throughout the body — never keyword-stuffed',
              '- Keyword density for primary keyword: 1–2% of total word count',
              '',
              'When calling create_entry, build the full `seo` component:',
              '',
              '```json',
              '{',
              '  "title": "<article title — primary keyword near the front>",',
              '  "content": "<markdown body with keywords placed per rules above>",',
              '  "discipline": "<one of: Technology | Thought Theatre | The Self — infer from topic>",',
              '  "seo": {',
              '    "title": "<50–60 chars — primary keyword first, power word, brand optional>",',
              '    "description": "<under 160 chars — primary keyword, clear value proposition, soft CTA>",',
              '    "keywords": "<primary, secondary1, secondary2, long-tail1, long-tail2, LSI1, LSI2 — comma-separated, ordered by importance>",',
              '    "canonicalURL": "https://dugleelabs.io/articles/<slug>",',
              '    "socialMediaTitle": "<under 70 chars — engaging, shareable, may differ from seoTitle>",',
              '    "socialDescription": "<under 200 chars — hook-driven, encourages clicks and shares>",',
              '    "preventIndexing": false',
              '  }',
              '}',
              '```',
              '',
              'The `discipline` field is required. Infer it from the topic:',
              '- "Technology" — software, AI, tools, engineering, developer topics',
              '- "Thought Theatre" — opinions, critiques, industry commentary, essays',
              '- "The Self" — personal growth, productivity, mindset, career',
            ].join('\n'),
          },
        },
      ],
    }),
  )

  server.prompt(
    'dugleelabs/list-drafts',
    'Show all unpublished draft entries for a content type',
    {
      contentType: z.string().describe('The Strapi content type to list drafts for'),
    },
    ({ contentType }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Please list all draft (unpublished) entries for the "${contentType}" content type in Strapi.`,
              '',
              `Use the list_entries tool with status "draft" and show me:`,
              '- Entry ID',
              '- Title or name field',
              '- When it was last updated',
              '- Any other key fields',
              '',
              'If there are many entries, show the first page and let me know how many total drafts exist.',
            ].join('\n'),
          },
        },
      ],
    }),
  )

  server.prompt(
    'dugleelabs/review-entry',
    'Fetch a Strapi entry and suggest improvements before publishing',
    {
      contentType: z.string().describe('The Strapi content type'),
      id: z.string().describe('The entry ID to review'),
    },
    ({ contentType, id }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Please fetch entry ${id} from the "${contentType}" content type and review it before publishing.`,
              '',
              'Use get_entry to fetch the content, then provide:',
              '1. A summary of what the entry covers',
              '2. Suggested improvements to the title, body, and meta description',
              '3. Any missing sections or content that should be added',
              '4. Grammar or clarity issues',
              '5. Whether it is ready to publish, or what changes are needed first',
            ].join('\n'),
          },
        },
      ],
    }),
  )
}
